package CallCenter.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptDefinitions = createDescriptorForDefinitions();
  /*package*/ final ConceptDescriptor myConceptOption = createDescriptorForOption();
  /*package*/ final ConceptDescriptor myConceptStart = createDescriptorForStart();
  /*package*/ final ConceptDescriptor myConceptState = createDescriptorForState();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDefinitions, myConceptOption, myConceptStart, myConceptState);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Definitions:
        return myConceptDefinitions;
      case LanguageConceptSwitch.Option:
        return myConceptOption;
      case LanguageConceptSwitch.Start:
        return myConceptStart;
      case LanguageConceptSwitch.State:
        return myConceptState;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForDefinitions() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CallCenter", "Definitions", 0x6944722215994f75L, 0x88df3f53f7bef1adL, 0x215a432991f222c1L);
    b.class_(false, false, false);
    b.origin("r:fbef02b1-4565-45c0-b708-b05d31c55e57(CallCenter.structure)/2403307196976865985");
    b.version(3);
    b.property("name", 0x215a432991f222c2L).type(PrimitiveTypeId.STRING).origin("2403307196976865986").done();
    b.property("value", 0x215a432991f222c4L).type(PrimitiveTypeId.INTEGER).origin("2403307196976865988").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOption() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CallCenter", "Option", 0x6944722215994f75L, 0x88df3f53f7bef1adL, 0x215a432991f124b8L);
    b.class_(false, false, false);
    b.origin("r:fbef02b1-4565-45c0-b708-b05d31c55e57(CallCenter.structure)/2403307196976800952");
    b.version(3);
    b.property("num", 0x215a432991f124b9L).type(PrimitiveTypeId.INTEGER).origin("2403307196976800953").done();
    b.property("call", 0x215a432991f124bbL).type(PrimitiveTypeId.STRING).origin("2403307196976800955").done();
    b.aggregate("definitions", 0x215a432991f222c7L).target(0x6944722215994f75L, 0x88df3f53f7bef1adL, 0x215a432991f222c1L).optional(true).ordered(true).multiple(true).origin("2403307196976865991").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStart() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CallCenter", "Start", 0x6944722215994f75L, 0x88df3f53f7bef1adL, 0x1452e4f23a407a05L);
    b.class_(false, false, true);
    b.origin("r:fbef02b1-4565-45c0-b708-b05d31c55e57(CallCenter.structure)/1464484557859355141");
    b.version(3);
    b.aggregate("states", 0x1452e4f23a407a06L).target(0x6944722215994f75L, 0x88df3f53f7bef1adL, 0x215a432991efef6cL).optional(false).ordered(true).multiple(true).origin("1464484557859355142").done();
    b.aggregate("definitions", 0x1452e4f23a40cb9cL).target(0x6944722215994f75L, 0x88df3f53f7bef1adL, 0x215a432991f222c1L).optional(false).ordered(true).multiple(true).origin("1464484557859376028").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForState() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CallCenter", "State", 0x6944722215994f75L, 0x88df3f53f7bef1adL, 0x215a432991efef6cL);
    b.class_(false, false, false);
    b.origin("r:fbef02b1-4565-45c0-b708-b05d31c55e57(CallCenter.structure)/2403307196976721772");
    b.version(3);
    b.property("call", 0x215a432991f124b2L).type(PrimitiveTypeId.STRING).origin("2403307196976800946").done();
    b.property("name", 0x1452e4f23a40c7f4L).type(PrimitiveTypeId.STRING).origin("1464484557859375092").done();
    b.aggregate("options", 0x215a432991f124beL).target(0x6944722215994f75L, 0x88df3f53f7bef1adL, 0x215a432991f124b8L).optional(false).ordered(true).multiple(true).origin("2403307196976800958").done();
    b.aggregate("definitions", 0x215a432991f222beL).target(0x6944722215994f75L, 0x88df3f53f7bef1adL, 0x215a432991f222c1L).optional(true).ordered(true).multiple(true).origin("2403307196976865982").done();
    return b.create();
  }
}
